// components/accel/light_tree/light_tree.glsl — the light tree's importance measure
// (fable-light-bvh §3.2). Ray-walk support lives here per the accel family rule
// (build shared-in-family, queries live with their domains); the WALKS themselves are
// generated by the lighting feature (baked bases), calling this one static function
// from BOTH the pick walk and the pmf walk — the adjacency discipline's shared core.
//
// v1.5 importance (fable-light-bvh §3.2 — the measured horizon upgrade; the probe
// showed 54–59% of selection mass wasted on below-horizon lights in cloud scenes):
//   q.n = 0:  I = Φ / d̂²                        (media; no orientation claim)
//   q.n ≠ 0:  I = Φ · cos(max(0, θi − θu)) / d̂²  (one-sided horizon term)
// with d̂² = max(d², (diag/2)², ε). θi = angle(n, direction to the cluster center);
// θu subtends the cluster's bounding sphere — the conservative "a light could sit
// anywhere in the box" allowance (Conty–Kulla; pbrt's cosSubClamped identity, sqrt
// only, no trig). A cluster is culled (importance 0) ONLY when its ENTIRE bounding
// sphere lies below the tangent plane — at a HEMISPHERE-support receiver every such
// light contributes exactly zero, so the cull is variance-only. THAT CLAIM IS THE
// QUERY'S: q.two_sided (fable-rough-dielectric §3.3) says the receiver's BSDF support
// is the whole sphere (rough glass), and then the cull is NOT licensed — it disarms
// and the shaping goes sign-agnostic. The registry-wide contract test pins the
// pairing, so a future sphere-support model cannot forget to say so.
// Inside the bounding sphere the orientation claim is meaningless → normal-free
// (pbrt's inside-the-bounds convention). The orientation-CONE term (θ_o/θ_e) stays
// deliberately absent — provably vacuous for sphere/point emitters.
// The d² clamp is Conty–Kulla's near-field rule in the dimensionally consistent
// SQUARED form — pbrt's book text compares d² to a LENGTH; we transcribe the math,
// not the typo. ε floors the degenerate case (p at a point light's own position).

float light_tree_importance(vec3 bmin, vec3 bmax, float phi, LightQuery q) {
    vec3 c = 0.5 * (bmin + bmax);
    vec3 e = bmax - bmin;
    vec3 d = c - q.p;
    float d2raw = dot(d, d);
    float diag2 = 0.25 * dot(e, e);
    float base = phi / max(d2raw, max(diag2, 1e-8));
    if (dot(q.n, q.n) < 0.5) return base;      // no orientation information
    // EXACT box-below-horizon cull (deviation from pbrt's sphere-cone-only test,
    // found by the half-space vitest): max over the box's corners of (x − p)·n is
    // dot(n, far − p) with `far` the per-axis sign-selected corner. Boxes here are
    // exact unions of their children's, so the cull is HEREDITARY — a descent can
    // never die mid-tree while any above-horizon light exists.
    vec3 far_c = mix(bmin, bmax, step(vec3(0.0), q.n));
    float h = dot(q.n, far_c - q.p);           // EXACT max of n·(x−p) over the box
    if (q.two_sided) {
        // Sphere support: the receiver scatters light arriving from EITHER side, so the
        // relevant quantity is max|n·(x−p)| over the box. The opposite extreme is the
        // same sign-selected corner for −n, which is the box's mirror partner of far_c —
        // no second mix needed. h_two ≥ 0 always (if every corner is below, the mirror
        // term is positive), so a two-sided query can never cull: bias-free by
        // construction, and h_two/dmax stays a valid lower bound on best-case |cos|.
        vec3 near_c = bmin + bmax - far_c;
        h = max(h, -dot(q.n, near_c - q.p));
    } else if (h <= 0.0) {
        return 0.0;
    }
    // Best-case-cosine shaping from the SAME corner machinery (the v1.5.1 refinement —
    // the sphere-based cos(θi−θu) was axis-anisotropic: every axis-aligned box straddles
    // a tilted horizon plane, so diagonal-facing receivers got mushy selection — the
    // measured "diamond"). max cosθ over the box ≤ min(1, h/dmin) with dmin the exact
    // point-to-box distance: direction-exact in BOTH factors, continuous with the cull
    // at h = 0 (no defensive floor needed — only the cull produces zero), and p inside
    // the box gives dmin = 0 → full weight (the no-claim case), all in fewer ops than
    // the trig chain it replaces.
    // Two direction-exact estimates, composed: the CENTER cosine discriminates
    // mostly-above from mostly-below among straddling boxes (it goes negative for the
    // latter — exactly what the saturating best-case bound cannot see), and the
    // corner lower bound h/dmax (> 0 whenever the cull passes: the best light in the
    // box is at least this frontal) floors it so survivors stay reachable. Both are
    // corner/center quantities — no sphere, no axis bias.
    float cos_c = dot(q.n, d) * inversesqrt(max(d2raw, 1e-12));
    if (q.two_sided) cos_c = abs(cos_c);       // frontal from either side (same discriminator)
    vec3 dmx = max(q.p - bmin, bmax - q.p);
    float lo = h * inversesqrt(max(dot(dmx, dmx), 1e-12));
    return base * min(1.0, max(cos_c, lo));
}
